/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package N3Gallery;

import N3Gallery.dao.ProductDao;
import N3Gallery.utils.Seeder;
import N3Gallery.view.HomeScene;
import N3Gallery.view.LoginScene;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public App() {
        DB.connect();
        new Seeder().run();
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        System.out.println(new ProductDao().getProducts().size());
        primaryStage.setScene(new HomeScene(primaryStage).getScene());
        primaryStage.setTitle("Home");
        primaryStage.setResizable(false);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
