/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package N3Gallery;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        VBox vBox = new VBox(new Label("Hello World!"));
        vBox.setAlignment(Pos.CENTER);
        primaryStage.setScene(new Scene(vBox, 600, 480));
        primaryStage.setTitle("Main");
        primaryStage.show();
    }

    public static void main(String[] args) {
        System.out.println(DB.checkDBDriver());
        DB.connect();

        if (DB.getConnection() != null) {
            System.out.println("Connection established to SQLite DB");

            try {
                PreparedStatement statement = DB.getConnection().prepareStatement("SELECT * FROM users");
                ResultSet rs = statement.executeQuery();
                while (rs.next()) {
                    System.out.println(rs.getString("name"));
                }
            } catch (SQLException e) {
                Logger.getAnonymousLogger().log(
                        Level.SEVERE,
                        LocalDateTime.now() + ": Could not load users from database.");
            }
        }

        launch();
    }
}
